package com.util.mydao_data_layer.GreenDaoSrcGen;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.util.mydao_data_layer.GreenDaoSrcGen.ContentItemDetailTable;
import com.util.mydao_data_layer.GreenDaoSrcGen.ContentItemDetailTableDao;
import com.util.mydao_data_layer.GreenDaoSrcGen.ContentItemLeadMediaTable;
import com.util.mydao_data_layer.GreenDaoSrcGen.ContentItemLeadMediaTableDao;
import com.util.mydao_data_layer.GreenDaoSrcGen.ContentItemMediaTable;
import com.util.mydao_data_layer.GreenDaoSrcGen.ContentItemMediaTableDao;
import com.util.mydao_data_layer.GreenDaoSrcGen.ContentItemsTable;
import com.util.mydao_data_layer.GreenDaoSrcGen.ContentItemsTableDao;
import com.util.mydao_data_layer.GreenDaoSrcGen.GalleryContentTable;
import com.util.mydao_data_layer.GreenDaoSrcGen.GalleryContentTableDao;
import com.util.mydao_data_layer.GreenDaoSrcGen.ImgFnameTable;
import com.util.mydao_data_layer.GreenDaoSrcGen.ImgFnameTableDao;
import com.util.mydao_data_layer.GreenDaoSrcGen.RelatedItemsTable;
import com.util.mydao_data_layer.GreenDaoSrcGen.RelatedItemsTableDao;
import com.util.mydao_data_layer.GreenDaoSrcGen.UrlImgFileTable;
import com.util.mydao_data_layer.GreenDaoSrcGen.UrlImgFileTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig imgFnameTableDaoConfig;
    private final DaoConfig urlImgFileTableDaoConfig;
    private final DaoConfig galleryContentTableDaoConfig;
    private final DaoConfig relatedItemsTableDaoConfig;
    private final DaoConfig contentItemLeadMediaTableDaoConfig;
    private final DaoConfig contentItemMediaTableDaoConfig;
    private final DaoConfig contentItemDetailTableDaoConfig;
    private final DaoConfig contentItemsTableDaoConfig;

    private final ImgFnameTableDao imgFnameTableDao;
    private final UrlImgFileTableDao urlImgFileTableDao;
    private final GalleryContentTableDao galleryContentTableDao;
    private final RelatedItemsTableDao relatedItemsTableDao;
    private final ContentItemLeadMediaTableDao contentItemLeadMediaTableDao;
    private final ContentItemMediaTableDao contentItemMediaTableDao;
    private final ContentItemDetailTableDao contentItemDetailTableDao;
    private final ContentItemsTableDao contentItemsTableDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        imgFnameTableDaoConfig = daoConfigMap.get(ImgFnameTableDao.class).clone();
        imgFnameTableDaoConfig.initIdentityScope(type);

        urlImgFileTableDaoConfig = daoConfigMap.get(UrlImgFileTableDao.class).clone();
        urlImgFileTableDaoConfig.initIdentityScope(type);

        galleryContentTableDaoConfig = daoConfigMap.get(GalleryContentTableDao.class).clone();
        galleryContentTableDaoConfig.initIdentityScope(type);

        relatedItemsTableDaoConfig = daoConfigMap.get(RelatedItemsTableDao.class).clone();
        relatedItemsTableDaoConfig.initIdentityScope(type);

        contentItemLeadMediaTableDaoConfig = daoConfigMap.get(ContentItemLeadMediaTableDao.class).clone();
        contentItemLeadMediaTableDaoConfig.initIdentityScope(type);

        contentItemMediaTableDaoConfig = daoConfigMap.get(ContentItemMediaTableDao.class).clone();
        contentItemMediaTableDaoConfig.initIdentityScope(type);

        contentItemDetailTableDaoConfig = daoConfigMap.get(ContentItemDetailTableDao.class).clone();
        contentItemDetailTableDaoConfig.initIdentityScope(type);

        contentItemsTableDaoConfig = daoConfigMap.get(ContentItemsTableDao.class).clone();
        contentItemsTableDaoConfig.initIdentityScope(type);

        imgFnameTableDao = new ImgFnameTableDao(imgFnameTableDaoConfig, this);
        urlImgFileTableDao = new UrlImgFileTableDao(urlImgFileTableDaoConfig, this);
        galleryContentTableDao = new GalleryContentTableDao(galleryContentTableDaoConfig, this);
        relatedItemsTableDao = new RelatedItemsTableDao(relatedItemsTableDaoConfig, this);
        contentItemLeadMediaTableDao = new ContentItemLeadMediaTableDao(contentItemLeadMediaTableDaoConfig, this);
        contentItemMediaTableDao = new ContentItemMediaTableDao(contentItemMediaTableDaoConfig, this);
        contentItemDetailTableDao = new ContentItemDetailTableDao(contentItemDetailTableDaoConfig, this);
        contentItemsTableDao = new ContentItemsTableDao(contentItemsTableDaoConfig, this);

        registerDao(ImgFnameTable.class, imgFnameTableDao);
        registerDao(UrlImgFileTable.class, urlImgFileTableDao);
        registerDao(GalleryContentTable.class, galleryContentTableDao);
        registerDao(RelatedItemsTable.class, relatedItemsTableDao);
        registerDao(ContentItemLeadMediaTable.class, contentItemLeadMediaTableDao);
        registerDao(ContentItemMediaTable.class, contentItemMediaTableDao);
        registerDao(ContentItemDetailTable.class, contentItemDetailTableDao);
        registerDao(ContentItemsTable.class, contentItemsTableDao);
    }
    
    public void clear() {
        imgFnameTableDaoConfig.getIdentityScope().clear();
        urlImgFileTableDaoConfig.getIdentityScope().clear();
        galleryContentTableDaoConfig.getIdentityScope().clear();
        relatedItemsTableDaoConfig.getIdentityScope().clear();
        contentItemLeadMediaTableDaoConfig.getIdentityScope().clear();
        contentItemMediaTableDaoConfig.getIdentityScope().clear();
        contentItemDetailTableDaoConfig.getIdentityScope().clear();
        contentItemsTableDaoConfig.getIdentityScope().clear();
    }

    public ImgFnameTableDao getImgFnameTableDao() {
        return imgFnameTableDao;
    }

    public UrlImgFileTableDao getUrlImgFileTableDao() {
        return urlImgFileTableDao;
    }

    public GalleryContentTableDao getGalleryContentTableDao() {
        return galleryContentTableDao;
    }

    public RelatedItemsTableDao getRelatedItemsTableDao() {
        return relatedItemsTableDao;
    }

    public ContentItemLeadMediaTableDao getContentItemLeadMediaTableDao() {
        return contentItemLeadMediaTableDao;
    }

    public ContentItemMediaTableDao getContentItemMediaTableDao() {
        return contentItemMediaTableDao;
    }

    public ContentItemDetailTableDao getContentItemDetailTableDao() {
        return contentItemDetailTableDao;
    }

    public ContentItemsTableDao getContentItemsTableDao() {
        return contentItemsTableDao;
    }

}
