package com.util.mydao_data_layer.GreenDaoSrcGen;
//THIS CODE IS NO LONGER GENERATED.
//
//// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS
//
//// KEEP INCLUDES - put your custom includes here
//// KEEP INCLUDES END
///**
// * Entity mapped to table IMG_DETAILS_TABLE.
// */
//public class ImgDetailsTable {
//
//    private Long id;
//    /** Not-null value. */
//    private String ImgCredit;
//    /** Not-null value. */
//    private String ImgCaption;
//
//    // KEEP FIELDS - put your custom fields here
//    // KEEP FIELDS END
//
//    public ImgDetailsTable() {
//    }
//
//    public ImgDetailsTable(Long id) {
//        this.id = id;
//    }
//
//    public ImgDetailsTable(Long id, String ImgCredit, String ImgCaption) {
//        this.id = id;
//        this.ImgCredit = ImgCredit;
//        this.ImgCaption = ImgCaption;
//    }
//
//    public Long getId() {
//        return id;
//    }
//
//    public void setId(Long id) {
//        this.id = id;
//    }
//
//    /** Not-null value. */
//    public String getImgCredit() {
//        return ImgCredit;
//    }
//
//    /** Not-null value; ensure this value is available before it is saved to the database. */
//    public void setImgCredit(String ImgCredit) {
//        this.ImgCredit = ImgCredit;
//    }
//
//    /** Not-null value. */
//    public String getImgCaption() {
//        return ImgCaption;
//    }
//
//    /** Not-null value; ensure this value is available before it is saved to the database. */
//    public void setImgCaption(String ImgCaption) {
//        this.ImgCaption = ImgCaption;
//    }
//
//    // KEEP METHODS - put your custom methods here
//    // KEEP METHODS END
//
//}
