package jmtechsvcs.myweatherapp.GreenDaoSrcGen;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CITY__WEATHER__CURR__COND__TABLE.
 */
public class City_Weather_Curr_Cond_Table {

    private long city_id;
    private Long curr_weather_id;
    private String curr_weather_main;
    private String curr_weather_desc;
    private String curr_weather_icon;
    private Double curr_main_temp;
    private Long curr_main_pressure;
    private Long curr_main_humidity;
    private Double curr_main_temp_min;
    private Double curr_main_temp_max;
    private Long curr_main_sea_level;
    private Long curr_main_grnd_level;
    private Double curr_wind_speed;
    private Long curr_wind_degs;
    private Long curr_clouds_all;
    private Long curr_rain_last3hrs;
    private Long curr_snow_last3hrs;
    private Long curr_data_calc_time;
    private Long curr_sys_sunrise_time;
    private Long curr_sys_sunset_time;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public City_Weather_Curr_Cond_Table() {
    }

    public City_Weather_Curr_Cond_Table(long city_id) {
        this.city_id = city_id;
    }

    public City_Weather_Curr_Cond_Table(long city_id, Long curr_weather_id, String curr_weather_main, String curr_weather_desc, String curr_weather_icon, Double curr_main_temp, Long curr_main_pressure, Long curr_main_humidity, Double curr_main_temp_min, Double curr_main_temp_max, Long curr_main_sea_level, Long curr_main_grnd_level, Double curr_wind_speed, Long curr_wind_degs, Long curr_clouds_all, Long curr_rain_last3hrs, Long curr_snow_last3hrs, Long curr_data_calc_time, Long curr_sys_sunrise_time, Long curr_sys_sunset_time) {
        this.city_id = city_id;
        this.curr_weather_id = curr_weather_id;
        this.curr_weather_main = curr_weather_main;
        this.curr_weather_desc = curr_weather_desc;
        this.curr_weather_icon = curr_weather_icon;
        this.curr_main_temp = curr_main_temp;
        this.curr_main_pressure = curr_main_pressure;
        this.curr_main_humidity = curr_main_humidity;
        this.curr_main_temp_min = curr_main_temp_min;
        this.curr_main_temp_max = curr_main_temp_max;
        this.curr_main_sea_level = curr_main_sea_level;
        this.curr_main_grnd_level = curr_main_grnd_level;
        this.curr_wind_speed = curr_wind_speed;
        this.curr_wind_degs = curr_wind_degs;
        this.curr_clouds_all = curr_clouds_all;
        this.curr_rain_last3hrs = curr_rain_last3hrs;
        this.curr_snow_last3hrs = curr_snow_last3hrs;
        this.curr_data_calc_time = curr_data_calc_time;
        this.curr_sys_sunrise_time = curr_sys_sunrise_time;
        this.curr_sys_sunset_time = curr_sys_sunset_time;
    }

    public long getCity_id() {
        return city_id;
    }

    public void setCity_id(long city_id) {
        this.city_id = city_id;
    }

    public Long getCurr_weather_id() {
        return curr_weather_id;
    }

    public void setCurr_weather_id(Long curr_weather_id) {
        this.curr_weather_id = curr_weather_id;
    }

    public String getCurr_weather_main() {
        return curr_weather_main;
    }

    public void setCurr_weather_main(String curr_weather_main) {
        this.curr_weather_main = curr_weather_main;
    }

    public String getCurr_weather_desc() {
        return curr_weather_desc;
    }

    public void setCurr_weather_desc(String curr_weather_desc) {
        this.curr_weather_desc = curr_weather_desc;
    }

    public String getCurr_weather_icon() {
        return curr_weather_icon;
    }

    public void setCurr_weather_icon(String curr_weather_icon) {
        this.curr_weather_icon = curr_weather_icon;
    }

    public Double getCurr_main_temp() {
        return curr_main_temp;
    }

    public void setCurr_main_temp(Double curr_main_temp) {
        this.curr_main_temp = curr_main_temp;
    }

    public Long getCurr_main_pressure() {
        return curr_main_pressure;
    }

    public void setCurr_main_pressure(Long curr_main_pressure) {
        this.curr_main_pressure = curr_main_pressure;
    }

    public Long getCurr_main_humidity() {
        return curr_main_humidity;
    }

    public void setCurr_main_humidity(Long curr_main_humidity) {
        this.curr_main_humidity = curr_main_humidity;
    }

    public Double getCurr_main_temp_min() {
        return curr_main_temp_min;
    }

    public void setCurr_main_temp_min(Double curr_main_temp_min) {
        this.curr_main_temp_min = curr_main_temp_min;
    }

    public Double getCurr_main_temp_max() {
        return curr_main_temp_max;
    }

    public void setCurr_main_temp_max(Double curr_main_temp_max) {
        this.curr_main_temp_max = curr_main_temp_max;
    }

    public Long getCurr_main_sea_level() {
        return curr_main_sea_level;
    }

    public void setCurr_main_sea_level(Long curr_main_sea_level) {
        this.curr_main_sea_level = curr_main_sea_level;
    }

    public Long getCurr_main_grnd_level() {
        return curr_main_grnd_level;
    }

    public void setCurr_main_grnd_level(Long curr_main_grnd_level) {
        this.curr_main_grnd_level = curr_main_grnd_level;
    }

    public Double getCurr_wind_speed() {
        return curr_wind_speed;
    }

    public void setCurr_wind_speed(Double curr_wind_speed) {
        this.curr_wind_speed = curr_wind_speed;
    }

    public Long getCurr_wind_degs() {
        return curr_wind_degs;
    }

    public void setCurr_wind_degs(Long curr_wind_degs) {
        this.curr_wind_degs = curr_wind_degs;
    }

    public Long getCurr_clouds_all() {
        return curr_clouds_all;
    }

    public void setCurr_clouds_all(Long curr_clouds_all) {
        this.curr_clouds_all = curr_clouds_all;
    }

    public Long getCurr_rain_last3hrs() {
        return curr_rain_last3hrs;
    }

    public void setCurr_rain_last3hrs(Long curr_rain_last3hrs) {
        this.curr_rain_last3hrs = curr_rain_last3hrs;
    }

    public Long getCurr_snow_last3hrs() {
        return curr_snow_last3hrs;
    }

    public void setCurr_snow_last3hrs(Long curr_snow_last3hrs) {
        this.curr_snow_last3hrs = curr_snow_last3hrs;
    }

    public Long getCurr_data_calc_time() {
        return curr_data_calc_time;
    }

    public void setCurr_data_calc_time(Long curr_data_calc_time) {
        this.curr_data_calc_time = curr_data_calc_time;
    }

    public Long getCurr_sys_sunrise_time() {
        return curr_sys_sunrise_time;
    }

    public void setCurr_sys_sunrise_time(Long curr_sys_sunrise_time) {
        this.curr_sys_sunrise_time = curr_sys_sunrise_time;
    }

    public Long getCurr_sys_sunset_time() {
        return curr_sys_sunset_time;
    }

    public void setCurr_sys_sunset_time(Long curr_sys_sunset_time) {
        this.curr_sys_sunset_time = curr_sys_sunset_time;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
