package jmtechsvcs.myweatherapp.GreenDaoSrcGen;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import jmtechsvcs.myweatherapp.GreenDaoSrcGen.CityInfoTable;

import jmtechsvcs.myweatherapp.GreenDaoSrcGen.CityInfoTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cityInfoTableDaoConfig;

    private final CityInfoTableDao cityInfoTableDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cityInfoTableDaoConfig = daoConfigMap.get(CityInfoTableDao.class).clone();
        cityInfoTableDaoConfig.initIdentityScope(type);

        cityInfoTableDao = new CityInfoTableDao(cityInfoTableDaoConfig, this);

        registerDao(CityInfoTable.class, cityInfoTableDao);
    }
    
    public void clear() {
        cityInfoTableDaoConfig.getIdentityScope().clear();
    }

    public CityInfoTableDao getCityInfoTableDao() {
        return cityInfoTableDao;
    }

}
