package jmtechsvcs.myweatherapp.GreenDaoSrcGen;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import jmtechsvcs.myweatherapp.GreenDaoSrcGen.CityInfoTable;
import jmtechsvcs.myweatherapp.GreenDaoSrcGen.City_Weather_Curr_Cond_Table;

import jmtechsvcs.myweatherapp.GreenDaoSrcGen.CityInfoTableDao;
import jmtechsvcs.myweatherapp.GreenDaoSrcGen.City_Weather_Curr_Cond_TableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cityInfoTableDaoConfig;
    private final DaoConfig city_Weather_Curr_Cond_TableDaoConfig;

    private final CityInfoTableDao cityInfoTableDao;
    private final City_Weather_Curr_Cond_TableDao city_Weather_Curr_Cond_TableDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cityInfoTableDaoConfig = daoConfigMap.get(CityInfoTableDao.class).clone();
        cityInfoTableDaoConfig.initIdentityScope(type);

        city_Weather_Curr_Cond_TableDaoConfig = daoConfigMap.get(City_Weather_Curr_Cond_TableDao.class).clone();
        city_Weather_Curr_Cond_TableDaoConfig.initIdentityScope(type);

        cityInfoTableDao = new CityInfoTableDao(cityInfoTableDaoConfig, this);
        city_Weather_Curr_Cond_TableDao = new City_Weather_Curr_Cond_TableDao(city_Weather_Curr_Cond_TableDaoConfig, this);

        registerDao(CityInfoTable.class, cityInfoTableDao);
        registerDao(City_Weather_Curr_Cond_Table.class, city_Weather_Curr_Cond_TableDao);
    }
    
    public void clear() {
        cityInfoTableDaoConfig.getIdentityScope().clear();
        city_Weather_Curr_Cond_TableDaoConfig.getIdentityScope().clear();
    }

    public CityInfoTableDao getCityInfoTableDao() {
        return cityInfoTableDao;
    }

    public City_Weather_Curr_Cond_TableDao getCity_Weather_Curr_Cond_TableDao() {
        return city_Weather_Curr_Cond_TableDao;
    }

}
