package jmtechsvcs.myweatherapp.greendaosrcgenpkg;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import jmtechsvcs.myweatherapp.greendaosrcgenpkg.CityWeatherCurrCondTable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CITY_WEATHER_CURR_COND_TABLE".
*/
public class CityWeatherCurrCondTableDao extends AbstractDao<CityWeatherCurrCondTable, Long> {

    public static final String TABLENAME = "CITY_WEATHER_CURR_COND_TABLE";

    /**
     * Properties of entity CityWeatherCurrCondTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property City_id = new Property(0, long.class, "city_id", true, "CITY_ID");
        public final static Property Curr_weather_id = new Property(1, long.class, "curr_weather_id", false, "CURR_WEATHER_ID");
        public final static Property Curr_weather_main = new Property(2, String.class, "curr_weather_main", false, "CURR_WEATHER_MAIN");
        public final static Property Curr_weather_desc = new Property(3, String.class, "curr_weather_desc", false, "CURR_WEATHER_DESC");
        public final static Property Curr_weather_icon = new Property(4, String.class, "curr_weather_icon", false, "CURR_WEATHER_ICON");
        public final static Property Curr_main_temp = new Property(5, double.class, "curr_main_temp", false, "CURR_MAIN_TEMP");
        public final static Property Curr_main_pressure = new Property(6, long.class, "curr_main_pressure", false, "CURR_MAIN_PRESSURE");
        public final static Property Curr_main_humidity = new Property(7, long.class, "curr_main_humidity", false, "CURR_MAIN_HUMIDITY");
        public final static Property Curr_main_temp_min = new Property(8, double.class, "curr_main_temp_min", false, "CURR_MAIN_TEMP_MIN");
        public final static Property Curr_main_temp_max = new Property(9, double.class, "curr_main_temp_max", false, "CURR_MAIN_TEMP_MAX");
        public final static Property Curr_main_sea_level = new Property(10, long.class, "curr_main_sea_level", false, "CURR_MAIN_SEA_LEVEL");
        public final static Property Curr_main_grnd_level = new Property(11, long.class, "curr_main_grnd_level", false, "CURR_MAIN_GRND_LEVEL");
        public final static Property Curr_wind_speed = new Property(12, double.class, "curr_wind_speed", false, "CURR_WIND_SPEED");
        public final static Property Curr_wind_degs = new Property(13, long.class, "curr_wind_degs", false, "CURR_WIND_DEGS");
        public final static Property Curr_wind_speed_name = new Property(14, String.class, "curr_wind_speed_name", false, "CURR_WIND_SPEED_NAME");
        public final static Property Curr_wind_dirr_code = new Property(15, String.class, "curr_wind_dirr_code", false, "CURR_WIND_DIRR_CODE");
        public final static Property Curr_clouds_all = new Property(16, long.class, "curr_clouds_all", false, "CURR_CLOUDS_ALL");
        public final static Property Curr_visibility = new Property(17, long.class, "curr_visibility", false, "CURR_VISIBILITY");
        public final static Property Precipitation_mode = new Property(18, String.class, "precipitation_mode", false, "PRECIPITATION_MODE");
        public final static Property Precipitation_value = new Property(19, double.class, "precipitation_value", false, "PRECIPITATION_VALUE");
        public final static Property Curr_rain_last3hrs = new Property(20, double.class, "curr_rain_last3hrs", false, "CURR_RAIN_LAST3HRS");
        public final static Property Curr_snow_last3hrs = new Property(21, double.class, "curr_snow_last3hrs", false, "CURR_SNOW_LAST3HRS");
        public final static Property Curr_data_calc_time = new Property(22, long.class, "curr_data_calc_time", false, "CURR_DATA_CALC_TIME");
        public final static Property Curr_sys_sunrise_time = new Property(23, long.class, "curr_sys_sunrise_time", false, "CURR_SYS_SUNRISE_TIME");
        public final static Property Curr_sys_sunset_time = new Property(24, long.class, "curr_sys_sunset_time", false, "CURR_SYS_SUNSET_TIME");
    };


    public CityWeatherCurrCondTableDao(DaoConfig config) {
        super(config);
    }
    
    public CityWeatherCurrCondTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CITY_WEATHER_CURR_COND_TABLE\" (" + //
                "\"CITY_ID\" INTEGER PRIMARY KEY NOT NULL ," + // 0: city_id
                "\"CURR_WEATHER_ID\" INTEGER NOT NULL ," + // 1: curr_weather_id
                "\"CURR_WEATHER_MAIN\" TEXT NOT NULL ," + // 2: curr_weather_main
                "\"CURR_WEATHER_DESC\" TEXT NOT NULL ," + // 3: curr_weather_desc
                "\"CURR_WEATHER_ICON\" TEXT NOT NULL ," + // 4: curr_weather_icon
                "\"CURR_MAIN_TEMP\" REAL NOT NULL ," + // 5: curr_main_temp
                "\"CURR_MAIN_PRESSURE\" INTEGER NOT NULL ," + // 6: curr_main_pressure
                "\"CURR_MAIN_HUMIDITY\" INTEGER NOT NULL ," + // 7: curr_main_humidity
                "\"CURR_MAIN_TEMP_MIN\" REAL NOT NULL ," + // 8: curr_main_temp_min
                "\"CURR_MAIN_TEMP_MAX\" REAL NOT NULL ," + // 9: curr_main_temp_max
                "\"CURR_MAIN_SEA_LEVEL\" INTEGER NOT NULL ," + // 10: curr_main_sea_level
                "\"CURR_MAIN_GRND_LEVEL\" INTEGER NOT NULL ," + // 11: curr_main_grnd_level
                "\"CURR_WIND_SPEED\" REAL NOT NULL ," + // 12: curr_wind_speed
                "\"CURR_WIND_DEGS\" INTEGER NOT NULL ," + // 13: curr_wind_degs
                "\"CURR_WIND_SPEED_NAME\" TEXT NOT NULL ," + // 14: curr_wind_speed_name
                "\"CURR_WIND_DIRR_CODE\" TEXT NOT NULL ," + // 15: curr_wind_dirr_code
                "\"CURR_CLOUDS_ALL\" INTEGER NOT NULL ," + // 16: curr_clouds_all
                "\"CURR_VISIBILITY\" INTEGER NOT NULL ," + // 17: curr_visibility
                "\"PRECIPITATION_MODE\" TEXT NOT NULL ," + // 18: precipitation_mode
                "\"PRECIPITATION_VALUE\" REAL NOT NULL ," + // 19: precipitation_value
                "\"CURR_RAIN_LAST3HRS\" REAL NOT NULL ," + // 20: curr_rain_last3hrs
                "\"CURR_SNOW_LAST3HRS\" REAL NOT NULL ," + // 21: curr_snow_last3hrs
                "\"CURR_DATA_CALC_TIME\" INTEGER NOT NULL ," + // 22: curr_data_calc_time
                "\"CURR_SYS_SUNRISE_TIME\" INTEGER NOT NULL ," + // 23: curr_sys_sunrise_time
                "\"CURR_SYS_SUNSET_TIME\" INTEGER NOT NULL );"); // 24: curr_sys_sunset_time
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CITY_WEATHER_CURR_COND_TABLE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CityWeatherCurrCondTable entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getCity_id());
        stmt.bindLong(2, entity.getCurr_weather_id());
        stmt.bindString(3, entity.getCurr_weather_main());
        stmt.bindString(4, entity.getCurr_weather_desc());
        stmt.bindString(5, entity.getCurr_weather_icon());
        stmt.bindDouble(6, entity.getCurr_main_temp());
        stmt.bindLong(7, entity.getCurr_main_pressure());
        stmt.bindLong(8, entity.getCurr_main_humidity());
        stmt.bindDouble(9, entity.getCurr_main_temp_min());
        stmt.bindDouble(10, entity.getCurr_main_temp_max());
        stmt.bindLong(11, entity.getCurr_main_sea_level());
        stmt.bindLong(12, entity.getCurr_main_grnd_level());
        stmt.bindDouble(13, entity.getCurr_wind_speed());
        stmt.bindLong(14, entity.getCurr_wind_degs());
        stmt.bindString(15, entity.getCurr_wind_speed_name());
        stmt.bindString(16, entity.getCurr_wind_dirr_code());
        stmt.bindLong(17, entity.getCurr_clouds_all());
        stmt.bindLong(18, entity.getCurr_visibility());
        stmt.bindString(19, entity.getPrecipitation_mode());
        stmt.bindDouble(20, entity.getPrecipitation_value());
        stmt.bindDouble(21, entity.getCurr_rain_last3hrs());
        stmt.bindDouble(22, entity.getCurr_snow_last3hrs());
        stmt.bindLong(23, entity.getCurr_data_calc_time());
        stmt.bindLong(24, entity.getCurr_sys_sunrise_time());
        stmt.bindLong(25, entity.getCurr_sys_sunset_time());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public CityWeatherCurrCondTable readEntity(Cursor cursor, int offset) {
        CityWeatherCurrCondTable entity = new CityWeatherCurrCondTable( //
            cursor.getLong(offset + 0), // city_id
            cursor.getLong(offset + 1), // curr_weather_id
            cursor.getString(offset + 2), // curr_weather_main
            cursor.getString(offset + 3), // curr_weather_desc
            cursor.getString(offset + 4), // curr_weather_icon
            cursor.getDouble(offset + 5), // curr_main_temp
            cursor.getLong(offset + 6), // curr_main_pressure
            cursor.getLong(offset + 7), // curr_main_humidity
            cursor.getDouble(offset + 8), // curr_main_temp_min
            cursor.getDouble(offset + 9), // curr_main_temp_max
            cursor.getLong(offset + 10), // curr_main_sea_level
            cursor.getLong(offset + 11), // curr_main_grnd_level
            cursor.getDouble(offset + 12), // curr_wind_speed
            cursor.getLong(offset + 13), // curr_wind_degs
            cursor.getString(offset + 14), // curr_wind_speed_name
            cursor.getString(offset + 15), // curr_wind_dirr_code
            cursor.getLong(offset + 16), // curr_clouds_all
            cursor.getLong(offset + 17), // curr_visibility
            cursor.getString(offset + 18), // precipitation_mode
            cursor.getDouble(offset + 19), // precipitation_value
            cursor.getDouble(offset + 20), // curr_rain_last3hrs
            cursor.getDouble(offset + 21), // curr_snow_last3hrs
            cursor.getLong(offset + 22), // curr_data_calc_time
            cursor.getLong(offset + 23), // curr_sys_sunrise_time
            cursor.getLong(offset + 24) // curr_sys_sunset_time
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CityWeatherCurrCondTable entity, int offset) {
        entity.setCity_id(cursor.getLong(offset + 0));
        entity.setCurr_weather_id(cursor.getLong(offset + 1));
        entity.setCurr_weather_main(cursor.getString(offset + 2));
        entity.setCurr_weather_desc(cursor.getString(offset + 3));
        entity.setCurr_weather_icon(cursor.getString(offset + 4));
        entity.setCurr_main_temp(cursor.getDouble(offset + 5));
        entity.setCurr_main_pressure(cursor.getLong(offset + 6));
        entity.setCurr_main_humidity(cursor.getLong(offset + 7));
        entity.setCurr_main_temp_min(cursor.getDouble(offset + 8));
        entity.setCurr_main_temp_max(cursor.getDouble(offset + 9));
        entity.setCurr_main_sea_level(cursor.getLong(offset + 10));
        entity.setCurr_main_grnd_level(cursor.getLong(offset + 11));
        entity.setCurr_wind_speed(cursor.getDouble(offset + 12));
        entity.setCurr_wind_degs(cursor.getLong(offset + 13));
        entity.setCurr_wind_speed_name(cursor.getString(offset + 14));
        entity.setCurr_wind_dirr_code(cursor.getString(offset + 15));
        entity.setCurr_clouds_all(cursor.getLong(offset + 16));
        entity.setCurr_visibility(cursor.getLong(offset + 17));
        entity.setPrecipitation_mode(cursor.getString(offset + 18));
        entity.setPrecipitation_value(cursor.getDouble(offset + 19));
        entity.setCurr_rain_last3hrs(cursor.getDouble(offset + 20));
        entity.setCurr_snow_last3hrs(cursor.getDouble(offset + 21));
        entity.setCurr_data_calc_time(cursor.getLong(offset + 22));
        entity.setCurr_sys_sunrise_time(cursor.getLong(offset + 23));
        entity.setCurr_sys_sunset_time(cursor.getLong(offset + 24));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(CityWeatherCurrCondTable entity, long rowId) {
        entity.setCity_id(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(CityWeatherCurrCondTable entity) {
        if(entity != null) {
            return entity.getCity_id();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
