package jmtechsvcs.myweatherapp.greendaosrcgenpkg;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DAILY_WEATHER_INFO_TABLE".
 */
public class DailyWeatherInfoTable {

    private Long id;
    private long city_id;
    private long daily_symbol_number;
    /** Not-null value. */
    private String daily_symbol_name;
    /** Not-null value. */
    private String daily_symbol_var;
    private double daily_precip_value;
    /** Not-null value. */
    private String daily_precip_type;
    /** Not-null value. */
    private String daily_precip_unit;
    private long daily_wind_dirr_deg;
    /** Not-null value. */
    private String daily_wind_dirr_code;
    /** Not-null value. */
    private String daily_wind_dirr_name;
    private double daily_wind_speed_mps;
    /** Not-null value. */
    private String daily_wind_speed_name;
    private double daily_temp;
    private double daily_min_temp;
    private double daily_max_temp;
    private double daily_night_temp;
    private double daily_evening_temp;
    private double daily_morning_temp;
    /** Not-null value. */
    private String daily_pressure_unit;
    private double daily_pressure_value;
    private long daily_humidity_val;
    /** Not-null value. */
    private String daily_humidity_unit;
    /** Not-null value. */
    private String daily_clouds_val;
    private double daily_clouds_all;
    /** Not-null value. */
    private String daily_clouds_unit;
    private long daily_weather_date;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DailyWeatherInfoTable() {
    }

    public DailyWeatherInfoTable(Long id) {
        this.id = id;
    }

    public DailyWeatherInfoTable(Long id, long city_id, long daily_symbol_number, String daily_symbol_name, String daily_symbol_var, double daily_precip_value, String daily_precip_type, String daily_precip_unit, long daily_wind_dirr_deg, String daily_wind_dirr_code, String daily_wind_dirr_name, double daily_wind_speed_mps, String daily_wind_speed_name, double daily_temp, double daily_min_temp, double daily_max_temp, double daily_night_temp, double daily_evening_temp, double daily_morning_temp, String daily_pressure_unit, double daily_pressure_value, long daily_humidity_val, String daily_humidity_unit, String daily_clouds_val, double daily_clouds_all, String daily_clouds_unit, long daily_weather_date) {
        this.id = id;
        this.city_id = city_id;
        this.daily_symbol_number = daily_symbol_number;
        this.daily_symbol_name = daily_symbol_name;
        this.daily_symbol_var = daily_symbol_var;
        this.daily_precip_value = daily_precip_value;
        this.daily_precip_type = daily_precip_type;
        this.daily_precip_unit = daily_precip_unit;
        this.daily_wind_dirr_deg = daily_wind_dirr_deg;
        this.daily_wind_dirr_code = daily_wind_dirr_code;
        this.daily_wind_dirr_name = daily_wind_dirr_name;
        this.daily_wind_speed_mps = daily_wind_speed_mps;
        this.daily_wind_speed_name = daily_wind_speed_name;
        this.daily_temp = daily_temp;
        this.daily_min_temp = daily_min_temp;
        this.daily_max_temp = daily_max_temp;
        this.daily_night_temp = daily_night_temp;
        this.daily_evening_temp = daily_evening_temp;
        this.daily_morning_temp = daily_morning_temp;
        this.daily_pressure_unit = daily_pressure_unit;
        this.daily_pressure_value = daily_pressure_value;
        this.daily_humidity_val = daily_humidity_val;
        this.daily_humidity_unit = daily_humidity_unit;
        this.daily_clouds_val = daily_clouds_val;
        this.daily_clouds_all = daily_clouds_all;
        this.daily_clouds_unit = daily_clouds_unit;
        this.daily_weather_date = daily_weather_date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getCity_id() {
        return city_id;
    }

    public void setCity_id(long city_id) {
        this.city_id = city_id;
    }

    public long getDaily_symbol_number() {
        return daily_symbol_number;
    }

    public void setDaily_symbol_number(long daily_symbol_number) {
        this.daily_symbol_number = daily_symbol_number;
    }

    /** Not-null value. */
    public String getDaily_symbol_name() {
        return daily_symbol_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDaily_symbol_name(String daily_symbol_name) {
        this.daily_symbol_name = daily_symbol_name;
    }

    /** Not-null value. */
    public String getDaily_symbol_var() {
        return daily_symbol_var;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDaily_symbol_var(String daily_symbol_var) {
        this.daily_symbol_var = daily_symbol_var;
    }

    public double getDaily_precip_value() {
        return daily_precip_value;
    }

    public void setDaily_precip_value(double daily_precip_value) {
        this.daily_precip_value = daily_precip_value;
    }

    /** Not-null value. */
    public String getDaily_precip_type() {
        return daily_precip_type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDaily_precip_type(String daily_precip_type) {
        this.daily_precip_type = daily_precip_type;
    }

    /** Not-null value. */
    public String getDaily_precip_unit() {
        return daily_precip_unit;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDaily_precip_unit(String daily_precip_unit) {
        this.daily_precip_unit = daily_precip_unit;
    }

    public long getDaily_wind_dirr_deg() {
        return daily_wind_dirr_deg;
    }

    public void setDaily_wind_dirr_deg(long daily_wind_dirr_deg) {
        this.daily_wind_dirr_deg = daily_wind_dirr_deg;
    }

    /** Not-null value. */
    public String getDaily_wind_dirr_code() {
        return daily_wind_dirr_code;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDaily_wind_dirr_code(String daily_wind_dirr_code) {
        this.daily_wind_dirr_code = daily_wind_dirr_code;
    }

    /** Not-null value. */
    public String getDaily_wind_dirr_name() {
        return daily_wind_dirr_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDaily_wind_dirr_name(String daily_wind_dirr_name) {
        this.daily_wind_dirr_name = daily_wind_dirr_name;
    }

    public double getDaily_wind_speed_mps() {
        return daily_wind_speed_mps;
    }

    public void setDaily_wind_speed_mps(double daily_wind_speed_mps) {
        this.daily_wind_speed_mps = daily_wind_speed_mps;
    }

    /** Not-null value. */
    public String getDaily_wind_speed_name() {
        return daily_wind_speed_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDaily_wind_speed_name(String daily_wind_speed_name) {
        this.daily_wind_speed_name = daily_wind_speed_name;
    }

    public double getDaily_temp() {
        return daily_temp;
    }

    public void setDaily_temp(double daily_temp) {
        this.daily_temp = daily_temp;
    }

    public double getDaily_min_temp() {
        return daily_min_temp;
    }

    public void setDaily_min_temp(double daily_min_temp) {
        this.daily_min_temp = daily_min_temp;
    }

    public double getDaily_max_temp() {
        return daily_max_temp;
    }

    public void setDaily_max_temp(double daily_max_temp) {
        this.daily_max_temp = daily_max_temp;
    }

    public double getDaily_night_temp() {
        return daily_night_temp;
    }

    public void setDaily_night_temp(double daily_night_temp) {
        this.daily_night_temp = daily_night_temp;
    }

    public double getDaily_evening_temp() {
        return daily_evening_temp;
    }

    public void setDaily_evening_temp(double daily_evening_temp) {
        this.daily_evening_temp = daily_evening_temp;
    }

    public double getDaily_morning_temp() {
        return daily_morning_temp;
    }

    public void setDaily_morning_temp(double daily_morning_temp) {
        this.daily_morning_temp = daily_morning_temp;
    }

    /** Not-null value. */
    public String getDaily_pressure_unit() {
        return daily_pressure_unit;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDaily_pressure_unit(String daily_pressure_unit) {
        this.daily_pressure_unit = daily_pressure_unit;
    }

    public double getDaily_pressure_value() {
        return daily_pressure_value;
    }

    public void setDaily_pressure_value(double daily_pressure_value) {
        this.daily_pressure_value = daily_pressure_value;
    }

    public long getDaily_humidity_val() {
        return daily_humidity_val;
    }

    public void setDaily_humidity_val(long daily_humidity_val) {
        this.daily_humidity_val = daily_humidity_val;
    }

    /** Not-null value. */
    public String getDaily_humidity_unit() {
        return daily_humidity_unit;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDaily_humidity_unit(String daily_humidity_unit) {
        this.daily_humidity_unit = daily_humidity_unit;
    }

    /** Not-null value. */
    public String getDaily_clouds_val() {
        return daily_clouds_val;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDaily_clouds_val(String daily_clouds_val) {
        this.daily_clouds_val = daily_clouds_val;
    }

    public double getDaily_clouds_all() {
        return daily_clouds_all;
    }

    public void setDaily_clouds_all(double daily_clouds_all) {
        this.daily_clouds_all = daily_clouds_all;
    }

    /** Not-null value. */
    public String getDaily_clouds_unit() {
        return daily_clouds_unit;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDaily_clouds_unit(String daily_clouds_unit) {
        this.daily_clouds_unit = daily_clouds_unit;
    }

    public long getDaily_weather_date() {
        return daily_weather_date;
    }

    public void setDaily_weather_date(long daily_weather_date) {
        this.daily_weather_date = daily_weather_date;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
