package jmtechsvcs.myweatherapp.greendaosrcgenpkg;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DAILY_WEATHER_INFO_TABLE".
 */
public class DailyWeatherInfoTable {

    private Long id;
    private long city_id;
    private Double daily_humidity;
    private Double daily_cloud_pert;
    private Double daily_pressure;
    private Double daily_rain;
    private Double daily_snow;
    private Double daily_wind_deg;
    private Double daily_wind_speed;
    private Double daily_temp;
    private Double daily_evening_temp;
    private Double daily_max_temp;
    private Double daily_min_temp;
    private Double daily_morning_temp;
    private Double daily_night_temp;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DailyWeatherInfoTable() {
    }

    public DailyWeatherInfoTable(Long id) {
        this.id = id;
    }

    public DailyWeatherInfoTable(Long id, long city_id, Double daily_humidity, Double daily_cloud_pert, Double daily_pressure, Double daily_rain, Double daily_snow, Double daily_wind_deg, Double daily_wind_speed, Double daily_temp, Double daily_evening_temp, Double daily_max_temp, Double daily_min_temp, Double daily_morning_temp, Double daily_night_temp) {
        this.id = id;
        this.city_id = city_id;
        this.daily_humidity = daily_humidity;
        this.daily_cloud_pert = daily_cloud_pert;
        this.daily_pressure = daily_pressure;
        this.daily_rain = daily_rain;
        this.daily_snow = daily_snow;
        this.daily_wind_deg = daily_wind_deg;
        this.daily_wind_speed = daily_wind_speed;
        this.daily_temp = daily_temp;
        this.daily_evening_temp = daily_evening_temp;
        this.daily_max_temp = daily_max_temp;
        this.daily_min_temp = daily_min_temp;
        this.daily_morning_temp = daily_morning_temp;
        this.daily_night_temp = daily_night_temp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getCity_id() {
        return city_id;
    }

    public void setCity_id(long city_id) {
        this.city_id = city_id;
    }

    public Double getDaily_humidity() {
        return daily_humidity;
    }

    public void setDaily_humidity(Double daily_humidity) {
        this.daily_humidity = daily_humidity;
    }

    public Double getDaily_cloud_pert() {
        return daily_cloud_pert;
    }

    public void setDaily_cloud_pert(Double daily_cloud_pert) {
        this.daily_cloud_pert = daily_cloud_pert;
    }

    public Double getDaily_pressure() {
        return daily_pressure;
    }

    public void setDaily_pressure(Double daily_pressure) {
        this.daily_pressure = daily_pressure;
    }

    public Double getDaily_rain() {
        return daily_rain;
    }

    public void setDaily_rain(Double daily_rain) {
        this.daily_rain = daily_rain;
    }

    public Double getDaily_snow() {
        return daily_snow;
    }

    public void setDaily_snow(Double daily_snow) {
        this.daily_snow = daily_snow;
    }

    public Double getDaily_wind_deg() {
        return daily_wind_deg;
    }

    public void setDaily_wind_deg(Double daily_wind_deg) {
        this.daily_wind_deg = daily_wind_deg;
    }

    public Double getDaily_wind_speed() {
        return daily_wind_speed;
    }

    public void setDaily_wind_speed(Double daily_wind_speed) {
        this.daily_wind_speed = daily_wind_speed;
    }

    public Double getDaily_temp() {
        return daily_temp;
    }

    public void setDaily_temp(Double daily_temp) {
        this.daily_temp = daily_temp;
    }

    public Double getDaily_evening_temp() {
        return daily_evening_temp;
    }

    public void setDaily_evening_temp(Double daily_evening_temp) {
        this.daily_evening_temp = daily_evening_temp;
    }

    public Double getDaily_max_temp() {
        return daily_max_temp;
    }

    public void setDaily_max_temp(Double daily_max_temp) {
        this.daily_max_temp = daily_max_temp;
    }

    public Double getDaily_min_temp() {
        return daily_min_temp;
    }

    public void setDaily_min_temp(Double daily_min_temp) {
        this.daily_min_temp = daily_min_temp;
    }

    public Double getDaily_morning_temp() {
        return daily_morning_temp;
    }

    public void setDaily_morning_temp(Double daily_morning_temp) {
        this.daily_morning_temp = daily_morning_temp;
    }

    public Double getDaily_night_temp() {
        return daily_night_temp;
    }

    public void setDaily_night_temp(Double daily_night_temp) {
        this.daily_night_temp = daily_night_temp;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
