package jmtechsvcs.myweatherapp.greendaosrcgenpkg;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DAILY_WEATHER_INFO_TABLE".
 */
public class DailyWeatherInfoTable {

    private Long id;
    private long city_id;
    private double daily_humidity;
    private double daily_cloud_pert;
    private double daily_pressure;
    private double daily_rain;
    private double daily_snow;
    private double daily_wind_deg;
    private double daily_wind_speed;
    private double daily_temp;
    private double daily_evening_temp;
    private double daily_max_temp;
    private double daily_min_temp;
    private double daily_morning_temp;
    private double daily_night_temp;
    private long daily_weather_date;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DailyWeatherInfoTable() {
    }

    public DailyWeatherInfoTable(Long id) {
        this.id = id;
    }

    public DailyWeatherInfoTable(Long id, long city_id, double daily_humidity, double daily_cloud_pert, double daily_pressure, double daily_rain, double daily_snow, double daily_wind_deg, double daily_wind_speed, double daily_temp, double daily_evening_temp, double daily_max_temp, double daily_min_temp, double daily_morning_temp, double daily_night_temp, long daily_weather_date) {
        this.id = id;
        this.city_id = city_id;
        this.daily_humidity = daily_humidity;
        this.daily_cloud_pert = daily_cloud_pert;
        this.daily_pressure = daily_pressure;
        this.daily_rain = daily_rain;
        this.daily_snow = daily_snow;
        this.daily_wind_deg = daily_wind_deg;
        this.daily_wind_speed = daily_wind_speed;
        this.daily_temp = daily_temp;
        this.daily_evening_temp = daily_evening_temp;
        this.daily_max_temp = daily_max_temp;
        this.daily_min_temp = daily_min_temp;
        this.daily_morning_temp = daily_morning_temp;
        this.daily_night_temp = daily_night_temp;
        this.daily_weather_date = daily_weather_date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getCity_id() {
        return city_id;
    }

    public void setCity_id(long city_id) {
        this.city_id = city_id;
    }

    public double getDaily_humidity() {
        return daily_humidity;
    }

    public void setDaily_humidity(double daily_humidity) {
        this.daily_humidity = daily_humidity;
    }

    public double getDaily_cloud_pert() {
        return daily_cloud_pert;
    }

    public void setDaily_cloud_pert(double daily_cloud_pert) {
        this.daily_cloud_pert = daily_cloud_pert;
    }

    public double getDaily_pressure() {
        return daily_pressure;
    }

    public void setDaily_pressure(double daily_pressure) {
        this.daily_pressure = daily_pressure;
    }

    public double getDaily_rain() {
        return daily_rain;
    }

    public void setDaily_rain(double daily_rain) {
        this.daily_rain = daily_rain;
    }

    public double getDaily_snow() {
        return daily_snow;
    }

    public void setDaily_snow(double daily_snow) {
        this.daily_snow = daily_snow;
    }

    public double getDaily_wind_deg() {
        return daily_wind_deg;
    }

    public void setDaily_wind_deg(double daily_wind_deg) {
        this.daily_wind_deg = daily_wind_deg;
    }

    public double getDaily_wind_speed() {
        return daily_wind_speed;
    }

    public void setDaily_wind_speed(double daily_wind_speed) {
        this.daily_wind_speed = daily_wind_speed;
    }

    public double getDaily_temp() {
        return daily_temp;
    }

    public void setDaily_temp(double daily_temp) {
        this.daily_temp = daily_temp;
    }

    public double getDaily_evening_temp() {
        return daily_evening_temp;
    }

    public void setDaily_evening_temp(double daily_evening_temp) {
        this.daily_evening_temp = daily_evening_temp;
    }

    public double getDaily_max_temp() {
        return daily_max_temp;
    }

    public void setDaily_max_temp(double daily_max_temp) {
        this.daily_max_temp = daily_max_temp;
    }

    public double getDaily_min_temp() {
        return daily_min_temp;
    }

    public void setDaily_min_temp(double daily_min_temp) {
        this.daily_min_temp = daily_min_temp;
    }

    public double getDaily_morning_temp() {
        return daily_morning_temp;
    }

    public void setDaily_morning_temp(double daily_morning_temp) {
        this.daily_morning_temp = daily_morning_temp;
    }

    public double getDaily_night_temp() {
        return daily_night_temp;
    }

    public void setDaily_night_temp(double daily_night_temp) {
        this.daily_night_temp = daily_night_temp;
    }

    public long getDaily_weather_date() {
        return daily_weather_date;
    }

    public void setDaily_weather_date(long daily_weather_date) {
        this.daily_weather_date = daily_weather_date;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
