package jmtechsvcs.myweatherapp.greendaosrcgenpkg;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import jmtechsvcs.myweatherapp.greendaosrcgenpkg.CityInfoTable;
import jmtechsvcs.myweatherapp.greendaosrcgenpkg.CityWeatherCurrCondTable;
import jmtechsvcs.myweatherapp.greendaosrcgenpkg.WeatherIconTable;
import jmtechsvcs.myweatherapp.greendaosrcgenpkg.WeatherStationInfoTable;
import jmtechsvcs.myweatherapp.greendaosrcgenpkg.DailyWeatherInfoTable;

import jmtechsvcs.myweatherapp.greendaosrcgenpkg.CityInfoTableDao;
import jmtechsvcs.myweatherapp.greendaosrcgenpkg.CityWeatherCurrCondTableDao;
import jmtechsvcs.myweatherapp.greendaosrcgenpkg.WeatherIconTableDao;
import jmtechsvcs.myweatherapp.greendaosrcgenpkg.WeatherStationInfoTableDao;
import jmtechsvcs.myweatherapp.greendaosrcgenpkg.DailyWeatherInfoTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cityInfoTableDaoConfig;
    private final DaoConfig cityWeatherCurrCondTableDaoConfig;
    private final DaoConfig weatherIconTableDaoConfig;
    private final DaoConfig weatherStationInfoTableDaoConfig;
    private final DaoConfig dailyWeatherInfoTableDaoConfig;

    private final CityInfoTableDao cityInfoTableDao;
    private final CityWeatherCurrCondTableDao cityWeatherCurrCondTableDao;
    private final WeatherIconTableDao weatherIconTableDao;
    private final WeatherStationInfoTableDao weatherStationInfoTableDao;
    private final DailyWeatherInfoTableDao dailyWeatherInfoTableDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cityInfoTableDaoConfig = daoConfigMap.get(CityInfoTableDao.class).clone();
        cityInfoTableDaoConfig.initIdentityScope(type);

        cityWeatherCurrCondTableDaoConfig = daoConfigMap.get(CityWeatherCurrCondTableDao.class).clone();
        cityWeatherCurrCondTableDaoConfig.initIdentityScope(type);

        weatherIconTableDaoConfig = daoConfigMap.get(WeatherIconTableDao.class).clone();
        weatherIconTableDaoConfig.initIdentityScope(type);

        weatherStationInfoTableDaoConfig = daoConfigMap.get(WeatherStationInfoTableDao.class).clone();
        weatherStationInfoTableDaoConfig.initIdentityScope(type);

        dailyWeatherInfoTableDaoConfig = daoConfigMap.get(DailyWeatherInfoTableDao.class).clone();
        dailyWeatherInfoTableDaoConfig.initIdentityScope(type);

        cityInfoTableDao = new CityInfoTableDao(cityInfoTableDaoConfig, this);
        cityWeatherCurrCondTableDao = new CityWeatherCurrCondTableDao(cityWeatherCurrCondTableDaoConfig, this);
        weatherIconTableDao = new WeatherIconTableDao(weatherIconTableDaoConfig, this);
        weatherStationInfoTableDao = new WeatherStationInfoTableDao(weatherStationInfoTableDaoConfig, this);
        dailyWeatherInfoTableDao = new DailyWeatherInfoTableDao(dailyWeatherInfoTableDaoConfig, this);

        registerDao(CityInfoTable.class, cityInfoTableDao);
        registerDao(CityWeatherCurrCondTable.class, cityWeatherCurrCondTableDao);
        registerDao(WeatherIconTable.class, weatherIconTableDao);
        registerDao(WeatherStationInfoTable.class, weatherStationInfoTableDao);
        registerDao(DailyWeatherInfoTable.class, dailyWeatherInfoTableDao);
    }
    
    public void clear() {
        cityInfoTableDaoConfig.getIdentityScope().clear();
        cityWeatherCurrCondTableDaoConfig.getIdentityScope().clear();
        weatherIconTableDaoConfig.getIdentityScope().clear();
        weatherStationInfoTableDaoConfig.getIdentityScope().clear();
        dailyWeatherInfoTableDaoConfig.getIdentityScope().clear();
    }

    public CityInfoTableDao getCityInfoTableDao() {
        return cityInfoTableDao;
    }

    public CityWeatherCurrCondTableDao getCityWeatherCurrCondTableDao() {
        return cityWeatherCurrCondTableDao;
    }

    public WeatherIconTableDao getWeatherIconTableDao() {
        return weatherIconTableDao;
    }

    public WeatherStationInfoTableDao getWeatherStationInfoTableDao() {
        return weatherStationInfoTableDao;
    }

    public DailyWeatherInfoTableDao getDailyWeatherInfoTableDao() {
        return dailyWeatherInfoTableDao;
    }

}
