package jmtechsvcs.myweatherapp.greendaosrcgenpkg;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "HOURLY_WEATHER_INFO_TABLE".
 */
public class HourlyWeatherInfoTable {

    private Long id;
    private long city_id;
    private long hourly_weather_date;
    private double hourly_cloud_pert;
    private double hourly_humidity;
    private double hourly_max_temp;
    private double hourly_min_temp;
    private double hourly_pressure;
    private double hourly_temp;
    private double hourly_sea_level;
    private double hourly_gnd_level;
    private double hourly_wind_deg;
    private double hourly_wind_speed;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public HourlyWeatherInfoTable() {
    }

    public HourlyWeatherInfoTable(Long id) {
        this.id = id;
    }

    public HourlyWeatherInfoTable(Long id, long city_id, long hourly_weather_date, double hourly_cloud_pert, double hourly_humidity, double hourly_max_temp, double hourly_min_temp, double hourly_pressure, double hourly_temp, double hourly_sea_level, double hourly_gnd_level, double hourly_wind_deg, double hourly_wind_speed) {
        this.id = id;
        this.city_id = city_id;
        this.hourly_weather_date = hourly_weather_date;
        this.hourly_cloud_pert = hourly_cloud_pert;
        this.hourly_humidity = hourly_humidity;
        this.hourly_max_temp = hourly_max_temp;
        this.hourly_min_temp = hourly_min_temp;
        this.hourly_pressure = hourly_pressure;
        this.hourly_temp = hourly_temp;
        this.hourly_sea_level = hourly_sea_level;
        this.hourly_gnd_level = hourly_gnd_level;
        this.hourly_wind_deg = hourly_wind_deg;
        this.hourly_wind_speed = hourly_wind_speed;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getCity_id() {
        return city_id;
    }

    public void setCity_id(long city_id) {
        this.city_id = city_id;
    }

    public long getHourly_weather_date() {
        return hourly_weather_date;
    }

    public void setHourly_weather_date(long hourly_weather_date) {
        this.hourly_weather_date = hourly_weather_date;
    }

    public double getHourly_cloud_pert() {
        return hourly_cloud_pert;
    }

    public void setHourly_cloud_pert(double hourly_cloud_pert) {
        this.hourly_cloud_pert = hourly_cloud_pert;
    }

    public double getHourly_humidity() {
        return hourly_humidity;
    }

    public void setHourly_humidity(double hourly_humidity) {
        this.hourly_humidity = hourly_humidity;
    }

    public double getHourly_max_temp() {
        return hourly_max_temp;
    }

    public void setHourly_max_temp(double hourly_max_temp) {
        this.hourly_max_temp = hourly_max_temp;
    }

    public double getHourly_min_temp() {
        return hourly_min_temp;
    }

    public void setHourly_min_temp(double hourly_min_temp) {
        this.hourly_min_temp = hourly_min_temp;
    }

    public double getHourly_pressure() {
        return hourly_pressure;
    }

    public void setHourly_pressure(double hourly_pressure) {
        this.hourly_pressure = hourly_pressure;
    }

    public double getHourly_temp() {
        return hourly_temp;
    }

    public void setHourly_temp(double hourly_temp) {
        this.hourly_temp = hourly_temp;
    }

    public double getHourly_sea_level() {
        return hourly_sea_level;
    }

    public void setHourly_sea_level(double hourly_sea_level) {
        this.hourly_sea_level = hourly_sea_level;
    }

    public double getHourly_gnd_level() {
        return hourly_gnd_level;
    }

    public void setHourly_gnd_level(double hourly_gnd_level) {
        this.hourly_gnd_level = hourly_gnd_level;
    }

    public double getHourly_wind_deg() {
        return hourly_wind_deg;
    }

    public void setHourly_wind_deg(double hourly_wind_deg) {
        this.hourly_wind_deg = hourly_wind_deg;
    }

    public double getHourly_wind_speed() {
        return hourly_wind_speed;
    }

    public void setHourly_wind_speed(double hourly_wind_speed) {
        this.hourly_wind_speed = hourly_wind_speed;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
