package jmtechsvcs.myweatherapp.greendaosrcgenpkg;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "WEATHER_STATION_INFO_TABLE".
 */
public class WeatherStationInfoTable {

    private long station_id;
    private long city_id;
    private double station_lat;
    private double station_lon;
    /** Not-null value. */
    private String station_name;
    private double station_temp;
    private long station_pressure;
    private long station_humidity;
    private double station_wind_speed;
    private long station_wind_deg;
    private double station_wind_gust;
    private long station_visibility_dist;
    private double station_calc_dewpt;
    private double station_calc_humidex;
    private long station_clouds_dist;
    /** Not-null value. */
    private String station_clouds_cond;
    private double station_rain_1h;
    private double station_rain_24h;
    private double station_rain_today;
    private long last_update_time;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public WeatherStationInfoTable() {
    }

    public WeatherStationInfoTable(long station_id) {
        this.station_id = station_id;
    }

    public WeatherStationInfoTable(long station_id, long city_id, double station_lat, double station_lon, String station_name, double station_temp, long station_pressure, long station_humidity, double station_wind_speed, long station_wind_deg, double station_wind_gust, long station_visibility_dist, double station_calc_dewpt, double station_calc_humidex, long station_clouds_dist, String station_clouds_cond, double station_rain_1h, double station_rain_24h, double station_rain_today, long last_update_time) {
        this.station_id = station_id;
        this.city_id = city_id;
        this.station_lat = station_lat;
        this.station_lon = station_lon;
        this.station_name = station_name;
        this.station_temp = station_temp;
        this.station_pressure = station_pressure;
        this.station_humidity = station_humidity;
        this.station_wind_speed = station_wind_speed;
        this.station_wind_deg = station_wind_deg;
        this.station_wind_gust = station_wind_gust;
        this.station_visibility_dist = station_visibility_dist;
        this.station_calc_dewpt = station_calc_dewpt;
        this.station_calc_humidex = station_calc_humidex;
        this.station_clouds_dist = station_clouds_dist;
        this.station_clouds_cond = station_clouds_cond;
        this.station_rain_1h = station_rain_1h;
        this.station_rain_24h = station_rain_24h;
        this.station_rain_today = station_rain_today;
        this.last_update_time = last_update_time;
    }

    public long getStation_id() {
        return station_id;
    }

    public void setStation_id(long station_id) {
        this.station_id = station_id;
    }

    public long getCity_id() {
        return city_id;
    }

    public void setCity_id(long city_id) {
        this.city_id = city_id;
    }

    public double getStation_lat() {
        return station_lat;
    }

    public void setStation_lat(double station_lat) {
        this.station_lat = station_lat;
    }

    public double getStation_lon() {
        return station_lon;
    }

    public void setStation_lon(double station_lon) {
        this.station_lon = station_lon;
    }

    /** Not-null value. */
    public String getStation_name() {
        return station_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStation_name(String station_name) {
        this.station_name = station_name;
    }

    public double getStation_temp() {
        return station_temp;
    }

    public void setStation_temp(double station_temp) {
        this.station_temp = station_temp;
    }

    public long getStation_pressure() {
        return station_pressure;
    }

    public void setStation_pressure(long station_pressure) {
        this.station_pressure = station_pressure;
    }

    public long getStation_humidity() {
        return station_humidity;
    }

    public void setStation_humidity(long station_humidity) {
        this.station_humidity = station_humidity;
    }

    public double getStation_wind_speed() {
        return station_wind_speed;
    }

    public void setStation_wind_speed(double station_wind_speed) {
        this.station_wind_speed = station_wind_speed;
    }

    public long getStation_wind_deg() {
        return station_wind_deg;
    }

    public void setStation_wind_deg(long station_wind_deg) {
        this.station_wind_deg = station_wind_deg;
    }

    public double getStation_wind_gust() {
        return station_wind_gust;
    }

    public void setStation_wind_gust(double station_wind_gust) {
        this.station_wind_gust = station_wind_gust;
    }

    public long getStation_visibility_dist() {
        return station_visibility_dist;
    }

    public void setStation_visibility_dist(long station_visibility_dist) {
        this.station_visibility_dist = station_visibility_dist;
    }

    public double getStation_calc_dewpt() {
        return station_calc_dewpt;
    }

    public void setStation_calc_dewpt(double station_calc_dewpt) {
        this.station_calc_dewpt = station_calc_dewpt;
    }

    public double getStation_calc_humidex() {
        return station_calc_humidex;
    }

    public void setStation_calc_humidex(double station_calc_humidex) {
        this.station_calc_humidex = station_calc_humidex;
    }

    public long getStation_clouds_dist() {
        return station_clouds_dist;
    }

    public void setStation_clouds_dist(long station_clouds_dist) {
        this.station_clouds_dist = station_clouds_dist;
    }

    /** Not-null value. */
    public String getStation_clouds_cond() {
        return station_clouds_cond;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStation_clouds_cond(String station_clouds_cond) {
        this.station_clouds_cond = station_clouds_cond;
    }

    public double getStation_rain_1h() {
        return station_rain_1h;
    }

    public void setStation_rain_1h(double station_rain_1h) {
        this.station_rain_1h = station_rain_1h;
    }

    public double getStation_rain_24h() {
        return station_rain_24h;
    }

    public void setStation_rain_24h(double station_rain_24h) {
        this.station_rain_24h = station_rain_24h;
    }

    public double getStation_rain_today() {
        return station_rain_today;
    }

    public void setStation_rain_today(double station_rain_today) {
        this.station_rain_today = station_rain_today;
    }

    public long getLast_update_time() {
        return last_update_time;
    }

    public void setLast_update_time(long last_update_time) {
        this.last_update_time = last_update_time;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
