package com.util.nbc_data_layer.nbcGreenDaoSrcGen;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CONTENT_ITEM_LEAD_MEDIA_TABLE.
 */
public class ContentItemLeadMediaTable {

    private long CmsID;
    /** Not-null value. */
    private String LeadMediaContentType;
    /** Not-null value. */
    private String LeadMediaThumbnail;
    /** Not-null value. */
    private String LeadMediaExtID;
    /** Not-null value. */
    private String LeadEmbeddedVideo;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ContentItemLeadMediaTable() {
    }

    public ContentItemLeadMediaTable(long CmsID) {
        this.CmsID = CmsID;
    }

    public ContentItemLeadMediaTable(long CmsID, String LeadMediaContentType, String LeadMediaThumbnail, String LeadMediaExtID, String LeadEmbeddedVideo) {
        this.CmsID = CmsID;
        this.LeadMediaContentType = LeadMediaContentType;
        this.LeadMediaThumbnail = LeadMediaThumbnail;
        this.LeadMediaExtID = LeadMediaExtID;
        this.LeadEmbeddedVideo = LeadEmbeddedVideo;
    }

    public long getCmsID() {
        return CmsID;
    }

    public void setCmsID(long CmsID) {
        this.CmsID = CmsID;
    }

    /** Not-null value. */
    public String getLeadMediaContentType() {
        return LeadMediaContentType;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLeadMediaContentType(String LeadMediaContentType) {
        this.LeadMediaContentType = LeadMediaContentType;
    }

    /** Not-null value. */
    public String getLeadMediaThumbnail() {
        return LeadMediaThumbnail;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLeadMediaThumbnail(String LeadMediaThumbnail) {
        this.LeadMediaThumbnail = LeadMediaThumbnail;
    }

    /** Not-null value. */
    public String getLeadMediaExtID() {
        return LeadMediaExtID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLeadMediaExtID(String LeadMediaExtID) {
        this.LeadMediaExtID = LeadMediaExtID;
    }

    /** Not-null value. */
    public String getLeadEmbeddedVideo() {
        return LeadEmbeddedVideo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLeadEmbeddedVideo(String LeadEmbeddedVideo) {
        this.LeadEmbeddedVideo = LeadEmbeddedVideo;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
