package com.util.nbc_data_layer.nbcGreenDaoSrcGen;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CONTENT_ITEM_MEDIA_TABLE.
 */
public class ContentItemMediaTable {

    private long CmsID;
    /** Not-null value. */
    private String Url;
    private int Width;
    private int Height;
    /** Not-null value. */
    private String ImageCredit;
    /** Not-null value. */
    private String PhotoThumbnail;
    /** Not-null value. */
    private String Thumbnail;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ContentItemMediaTable() {
    }

    public ContentItemMediaTable(long CmsID) {
        this.CmsID = CmsID;
    }

    public ContentItemMediaTable(long CmsID, String Url, int Width, int Height, String ImageCredit, String PhotoThumbnail, String Thumbnail) {
        this.CmsID = CmsID;
        this.Url = Url;
        this.Width = Width;
        this.Height = Height;
        this.ImageCredit = ImageCredit;
        this.PhotoThumbnail = PhotoThumbnail;
        this.Thumbnail = Thumbnail;
    }

    public long getCmsID() {
        return CmsID;
    }

    public void setCmsID(long CmsID) {
        this.CmsID = CmsID;
    }

    /** Not-null value. */
    public String getUrl() {
        return Url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String Url) {
        this.Url = Url;
    }

    public int getWidth() {
        return Width;
    }

    public void setWidth(int Width) {
        this.Width = Width;
    }

    public int getHeight() {
        return Height;
    }

    public void setHeight(int Height) {
        this.Height = Height;
    }

    /** Not-null value. */
    public String getImageCredit() {
        return ImageCredit;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImageCredit(String ImageCredit) {
        this.ImageCredit = ImageCredit;
    }

    /** Not-null value. */
    public String getPhotoThumbnail() {
        return PhotoThumbnail;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPhotoThumbnail(String PhotoThumbnail) {
        this.PhotoThumbnail = PhotoThumbnail;
    }

    /** Not-null value. */
    public String getThumbnail() {
        return Thumbnail;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setThumbnail(String Thumbnail) {
        this.Thumbnail = Thumbnail;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
