package com.util.nbc_data_layer.nbcGreenDaoSrcGen;


import com.util.nbc_data_layer.nbcGreenDaoSrcGen.DaoSession;

import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS



// KEEP INCLUDES - put your custom includes here
import com.util.nbc_data_layer.EntityItemIface;
import com.util.nbc_data_layer.EntityVisitorIface;
import com.util.nbc_data_layer.NBCDataBaseHelper.T_UrlTypeToId;
import com.util.nbc_data_layer.dataTypes.GalleryCntTypeIface;
//public class GalleryContentTable implements EntityItemIface, GalleryCntTypeIface{
// KEEP INCLUDES END
/**
 * Entity mapped to table GALLERY_CONTENT_TABLE.
 */
public class GalleryContentTable implements EntityItemIface, GalleryCntTypeIface{

    private Long id;
    private long GalCmsID;
    private long ImgIndex;
    private long imgFnameID;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient GalleryContentTableDao myDao;

    private ImgFnameTable imgFnameTable;
    private Long imgFnameTable__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public GalleryContentTable() {
    }

    public GalleryContentTable(Long id) {
        this.id = id;
    }

    public GalleryContentTable(Long id, long GalCmsID, long ImgIndex, long imgFnameID) {
        this.id = id;
        this.GalCmsID = GalCmsID;
        this.ImgIndex = ImgIndex;
        this.imgFnameID = imgFnameID;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getGalleryContentTableDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getGalCmsID() {
        return GalCmsID;
    }

    public void setGalCmsID(long GalCmsID) {
        this.GalCmsID = GalCmsID;
    }

    public long getImgIndex() {
        return ImgIndex;
    }

    public void setImgIndex(long ImgIndex) {
        this.ImgIndex = ImgIndex;
    }

    public long getImgFnameID() {
        return imgFnameID;
    }

    public void setImgFnameID(long imgFnameID) {
        this.imgFnameID = imgFnameID;
    }

    /** To-one relationship, resolved on first access. */
    public ImgFnameTable getImgFnameTable() {
        long __key = this.imgFnameID;
        if (imgFnameTable__resolvedKey == null || !imgFnameTable__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ImgFnameTableDao targetDao = daoSession.getImgFnameTableDao();
            ImgFnameTable imgFnameTableNew = targetDao.load(__key);
            synchronized (this) {
                imgFnameTable = imgFnameTableNew;
            	imgFnameTable__resolvedKey = __key;
            }
        }
        return imgFnameTable;
    }

    public void setImgFnameTable(ImgFnameTable imgFnameTable) {
        if (imgFnameTable == null) {
            throw new DaoException("To-one property 'imgFnameID' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.imgFnameTable = imgFnameTable;
            imgFnameID = imgFnameTable.getId();
            imgFnameTable__resolvedKey = imgFnameID;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
	@Override
	public void accept(EntityVisitorIface entityVisitorIface, T_UrlTypeToId typeID, UrlImgFileTable urlImgFileTable) 
	{
		//entityVisitorIface.visit(this,typeID,urlImgFileTable);
		//dont do anything here.
	}

	@Override
	public void accept(EntityVisitorIface entityVisitorIface, DaoSession daoSession, ContentItemsTable cntItemsTable) 
	{
		//dont do anything here
	}

	@Override
	public void accept(EntityVisitorIface entityVisitorIface, DaoSession daoSession) 
	{
		entityVisitorIface.visit(this, daoSession);
	}
	
	 /*
     * this is used for debugging purposes. this will return a string that contains the info
     * for this current obj as a string..for display. 
     */
	public String getDebugString()
	{
		StringBuilder sb = new StringBuilder();

    	sb.append("GalleryCntRowId = ");
    	sb.append(id);
    	sb.append(" ");
    	
    	sb.append("GalCmsID = ");
    	sb.append(GalCmsID);
    	sb.append(" ");
    	
    	sb.append("ImgIndex = ");
    	sb.append(ImgIndex);
    	sb.append(" ");
    	
    	//attempt to load using internal id..
    	if(imgFnameTable == null)
    		this.getImgFnameTable();
    	
    	if(imgFnameTable != null)
    	{
    		sb.append(imgFnameTable.getDebugString());
    	}
		
		return sb.toString();
	}
    // KEEP METHODS END

}
