package com.util.nbc_data_layer.nbcGreenDaoSrcGen;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.util.nbc_data_layer.nbcGreenDaoSrcGen.GalleryContentTable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table GALLERY_CONTENT_TABLE.
*/
public class GalleryContentTableDao extends AbstractDao<GalleryContentTable, Long> {

    public static final String TABLENAME = "GALLERY_CONTENT_TABLE";

    /**
     * Properties of entity GalleryContentTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property GalCmsID = new Property(0, long.class, "GalCmsID", true, "GAL_CMS_ID");
        public final static Property ImgIndex = new Property(1, int.class, "ImgIndex", false, "IMG_INDEX");
        public final static Property ImgPath = new Property(2, String.class, "ImgPath", false, "IMG_PATH");
    };


    public GalleryContentTableDao(DaoConfig config) {
        super(config);
    }
    
    public GalleryContentTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'GALLERY_CONTENT_TABLE' (" + //
                "'GAL_CMS_ID' INTEGER PRIMARY KEY NOT NULL ," + // 0: GalCmsID
                "'IMG_INDEX' INTEGER NOT NULL ," + // 1: ImgIndex
                "'IMG_PATH' TEXT NOT NULL );"); // 2: ImgPath
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'GALLERY_CONTENT_TABLE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GalleryContentTable entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getGalCmsID());
        stmt.bindLong(2, entity.getImgIndex());
        stmt.bindString(3, entity.getImgPath());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public GalleryContentTable readEntity(Cursor cursor, int offset) {
        GalleryContentTable entity = new GalleryContentTable( //
            cursor.getLong(offset + 0), // GalCmsID
            cursor.getInt(offset + 1), // ImgIndex
            cursor.getString(offset + 2) // ImgPath
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GalleryContentTable entity, int offset) {
        entity.setGalCmsID(cursor.getLong(offset + 0));
        entity.setImgIndex(cursor.getInt(offset + 1));
        entity.setImgPath(cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(GalleryContentTable entity, long rowId) {
        entity.setGalCmsID(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(GalleryContentTable entity) {
        if(entity != null) {
            return entity.getGalCmsID();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
