package com.util.nbc_data_layer.nbcGreenDaoSrcGen;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table GALLERY_CONTENT_TABLE.
 */
public class GalleryContentTable {

    private long GalCmsID;
    private int ImgHeight;
    private int ImgWidth;
    private int ImgIndex;
    /** Not-null value. */
    private String ImgPath;
    /** Not-null value. */
    private String ImgCaption;
    /** Not-null value. */
    private String ImgCredit;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public GalleryContentTable() {
    }

    public GalleryContentTable(long GalCmsID) {
        this.GalCmsID = GalCmsID;
    }

    public GalleryContentTable(long GalCmsID, int ImgHeight, int ImgWidth, int ImgIndex, String ImgPath, String ImgCaption, String ImgCredit) {
        this.GalCmsID = GalCmsID;
        this.ImgHeight = ImgHeight;
        this.ImgWidth = ImgWidth;
        this.ImgIndex = ImgIndex;
        this.ImgPath = ImgPath;
        this.ImgCaption = ImgCaption;
        this.ImgCredit = ImgCredit;
    }

    public long getGalCmsID() {
        return GalCmsID;
    }

    public void setGalCmsID(long GalCmsID) {
        this.GalCmsID = GalCmsID;
    }

    public int getImgHeight() {
        return ImgHeight;
    }

    public void setImgHeight(int ImgHeight) {
        this.ImgHeight = ImgHeight;
    }

    public int getImgWidth() {
        return ImgWidth;
    }

    public void setImgWidth(int ImgWidth) {
        this.ImgWidth = ImgWidth;
    }

    public int getImgIndex() {
        return ImgIndex;
    }

    public void setImgIndex(int ImgIndex) {
        this.ImgIndex = ImgIndex;
    }

    /** Not-null value. */
    public String getImgPath() {
        return ImgPath;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImgPath(String ImgPath) {
        this.ImgPath = ImgPath;
    }

    /** Not-null value. */
    public String getImgCaption() {
        return ImgCaption;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImgCaption(String ImgCaption) {
        this.ImgCaption = ImgCaption;
    }

    /** Not-null value. */
    public String getImgCredit() {
        return ImgCredit;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImgCredit(String ImgCredit) {
        this.ImgCredit = ImgCredit;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
