package com.util.nbc_data_layer.nbcGreenDaoSrcGen;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table IMG_DETAILS_TABLE.
 */
public class ImgDetailsTable {

    private long id;
    private long ImgHeight;
    private long ImgWidth;
    /** Not-null value. */
    private String ImgCredit;
    /** Not-null value. */
    private String ImgCaption;
    /** Not-null value. */
    private String ImgExtension;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ImgDetailsTable() {
    }

    public ImgDetailsTable(long id) {
        this.id = id;
    }

    public ImgDetailsTable(long id, long ImgHeight, long ImgWidth, String ImgCredit, String ImgCaption, String ImgExtension) {
        this.id = id;
        this.ImgHeight = ImgHeight;
        this.ImgWidth = ImgWidth;
        this.ImgCredit = ImgCredit;
        this.ImgCaption = ImgCaption;
        this.ImgExtension = ImgExtension;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getImgHeight() {
        return ImgHeight;
    }

    public void setImgHeight(long ImgHeight) {
        this.ImgHeight = ImgHeight;
    }

    public long getImgWidth() {
        return ImgWidth;
    }

    public void setImgWidth(long ImgWidth) {
        this.ImgWidth = ImgWidth;
    }

    /** Not-null value. */
    public String getImgCredit() {
        return ImgCredit;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImgCredit(String ImgCredit) {
        this.ImgCredit = ImgCredit;
    }

    /** Not-null value. */
    public String getImgCaption() {
        return ImgCaption;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImgCaption(String ImgCaption) {
        this.ImgCaption = ImgCaption;
    }

    /** Not-null value. */
    public String getImgExtension() {
        return ImgExtension;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImgExtension(String ImgExtension) {
        this.ImgExtension = ImgExtension;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
