package com.util.nbc_data_layer.nbcGreenDaoSrcGen;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table IMG_FNAME_TABLE.
 */
public class ImgFnameTable {

    private long ImgFnameID;
    /** Not-null value. */
    private String ImageFname;
    private int ImgFileRefCount;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ImgFnameTable() {
    }

    public ImgFnameTable(long ImgFnameID) {
        this.ImgFnameID = ImgFnameID;
    }

    public ImgFnameTable(long ImgFnameID, String ImageFname, int ImgFileRefCount) {
        this.ImgFnameID = ImgFnameID;
        this.ImageFname = ImageFname;
        this.ImgFileRefCount = ImgFileRefCount;
    }

    public long getImgFnameID() {
        return ImgFnameID;
    }

    public void setImgFnameID(long ImgFnameID) {
        this.ImgFnameID = ImgFnameID;
    }

    /** Not-null value. */
    public String getImageFname() {
        return ImageFname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImageFname(String ImageFname) {
        this.ImageFname = ImageFname;
    }

    public int getImgFileRefCount() {
        return ImgFileRefCount;
    }

    public void setImgFileRefCount(int ImgFileRefCount) {
        this.ImgFileRefCount = ImgFileRefCount;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
