package com.util.nbc_data_layer.nbcGreenDaoSrcGen;


// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import com.util.nbc_data_layer.dataTypes.ImgFnameTypeIface;
//public class ImgFnameTable implements ImgFnameTypeIface{
// KEEP INCLUDES END
/**
 * Entity mapped to table IMG_FNAME_TABLE.
 */
public class ImgFnameTable implements ImgFnameTypeIface{

    private Long id;
    /** Not-null value. */
    private String ImgFname;
    private long ImgWidth;
    private long ImgHeight;
    /** Not-null value. */
    private String ImgCaption;
    /** Not-null value. */
    private String ImgCredit;
    /** Not-null value. */
    private String ImgUrlLocation;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ImgFnameTable() {
    }

    public ImgFnameTable(Long id) {
        this.id = id;
    }

    public ImgFnameTable(Long id, String ImgFname, long ImgWidth, long ImgHeight, String ImgCaption, String ImgCredit, String ImgUrlLocation) {
        this.id = id;
        this.ImgFname = ImgFname;
        this.ImgWidth = ImgWidth;
        this.ImgHeight = ImgHeight;
        this.ImgCaption = ImgCaption;
        this.ImgCredit = ImgCredit;
        this.ImgUrlLocation = ImgUrlLocation;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getImgFname() {
        return ImgFname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImgFname(String ImgFname) {
        this.ImgFname = ImgFname;
    }

    public long getImgWidth() {
        return ImgWidth;
    }

    public void setImgWidth(long ImgWidth) {
        this.ImgWidth = ImgWidth;
    }

    public long getImgHeight() {
        return ImgHeight;
    }

    public void setImgHeight(long ImgHeight) {
        this.ImgHeight = ImgHeight;
    }

    /** Not-null value. */
    public String getImgCaption() {
        return ImgCaption;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImgCaption(String ImgCaption) {
        this.ImgCaption = ImgCaption;
    }

    /** Not-null value. */
    public String getImgCredit() {
        return ImgCredit;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImgCredit(String ImgCredit) {
        this.ImgCredit = ImgCredit;
    }

    /** Not-null value. */
    public String getImgUrlLocation() {
        return ImgUrlLocation;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImgUrlLocation(String ImgUrlLocation) {
        this.ImgUrlLocation = ImgUrlLocation;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
