package com.util.nbc_data_layer.nbcGreenDaoSrcGen;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table RELATED_ITEMS_TABLE.
 */
public class RelatedItemsTable {

    private long ParentCmsID;
    private int RelCmsID;
    /** Not-null value. */
    private String ContentType;
    /** Not-null value. */
    private String Title;
    private boolean Sponsored;
    /** Not-null value. */
    private String Source;
    /** Not-null value. */
    private String MobileThumbnailUrl;
    /** Not-null value. */
    private String StoryThumbnailUrl;
    /** Not-null value. */
    private String SharingUrl;
    private int TypeID;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public RelatedItemsTable() {
    }

    public RelatedItemsTable(long ParentCmsID) {
        this.ParentCmsID = ParentCmsID;
    }

    public RelatedItemsTable(long ParentCmsID, int RelCmsID, String ContentType, String Title, boolean Sponsored, String Source, String MobileThumbnailUrl, String StoryThumbnailUrl, String SharingUrl, int TypeID) {
        this.ParentCmsID = ParentCmsID;
        this.RelCmsID = RelCmsID;
        this.ContentType = ContentType;
        this.Title = Title;
        this.Sponsored = Sponsored;
        this.Source = Source;
        this.MobileThumbnailUrl = MobileThumbnailUrl;
        this.StoryThumbnailUrl = StoryThumbnailUrl;
        this.SharingUrl = SharingUrl;
        this.TypeID = TypeID;
    }

    public long getParentCmsID() {
        return ParentCmsID;
    }

    public void setParentCmsID(long ParentCmsID) {
        this.ParentCmsID = ParentCmsID;
    }

    public int getRelCmsID() {
        return RelCmsID;
    }

    public void setRelCmsID(int RelCmsID) {
        this.RelCmsID = RelCmsID;
    }

    /** Not-null value. */
    public String getContentType() {
        return ContentType;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContentType(String ContentType) {
        this.ContentType = ContentType;
    }

    /** Not-null value. */
    public String getTitle() {
        return Title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String Title) {
        this.Title = Title;
    }

    public boolean getSponsored() {
        return Sponsored;
    }

    public void setSponsored(boolean Sponsored) {
        this.Sponsored = Sponsored;
    }

    /** Not-null value. */
    public String getSource() {
        return Source;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSource(String Source) {
        this.Source = Source;
    }

    /** Not-null value. */
    public String getMobileThumbnailUrl() {
        return MobileThumbnailUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMobileThumbnailUrl(String MobileThumbnailUrl) {
        this.MobileThumbnailUrl = MobileThumbnailUrl;
    }

    /** Not-null value. */
    public String getStoryThumbnailUrl() {
        return StoryThumbnailUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStoryThumbnailUrl(String StoryThumbnailUrl) {
        this.StoryThumbnailUrl = StoryThumbnailUrl;
    }

    /** Not-null value. */
    public String getSharingUrl() {
        return SharingUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSharingUrl(String SharingUrl) {
        this.SharingUrl = SharingUrl;
    }

    public int getTypeID() {
        return TypeID;
    }

    public void setTypeID(int TypeID) {
        this.TypeID = TypeID;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
