package com.util.nbc_data_layer.nbcGreenDaoSrcGen;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.util.nbc_data_layer.nbcGreenDaoSrcGen.UrlImgFileTable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table URL_IMG_FILE_TABLE.
*/
public class UrlImgFileTableDao extends AbstractDao<UrlImgFileTable, Long> {

    public static final String TABLENAME = "URL_IMG_FILE_TABLE";

    /**
     * Properties of entity UrlImgFileTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CmsID = new Property(1, long.class, "CmsID", false, "CMS_ID");
        public final static Property UrlTypeID = new Property(2, long.class, "UrlTypeID", false, "URL_TYPE_ID");
        public final static Property UrlLocation = new Property(3, String.class, "UrlLocation", false, "URL_LOCATION");
        public final static Property ImgFnameID = new Property(4, long.class, "ImgFnameID", false, "IMG_FNAME_ID");
    };

    private DaoSession daoSession;


    public UrlImgFileTableDao(DaoConfig config) {
        super(config);
    }
    
    public UrlImgFileTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'URL_IMG_FILE_TABLE' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'CMS_ID' INTEGER NOT NULL ," + // 1: CmsID
                "'URL_TYPE_ID' INTEGER NOT NULL ," + // 2: UrlTypeID
                "'URL_LOCATION' TEXT NOT NULL ," + // 3: UrlLocation
                "'IMG_FNAME_ID' INTEGER NOT NULL );"); // 4: ImgFnameID
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'URL_IMG_FILE_TABLE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, UrlImgFileTable entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCmsID());
        stmt.bindLong(3, entity.getUrlTypeID());
        stmt.bindString(4, entity.getUrlLocation());
        stmt.bindLong(5, entity.getImgFnameID());
    }

    @Override
    protected void attachEntity(UrlImgFileTable entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public UrlImgFileTable readEntity(Cursor cursor, int offset) {
        UrlImgFileTable entity = new UrlImgFileTable( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // CmsID
            cursor.getLong(offset + 2), // UrlTypeID
            cursor.getString(offset + 3), // UrlLocation
            cursor.getLong(offset + 4) // ImgFnameID
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, UrlImgFileTable entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCmsID(cursor.getLong(offset + 1));
        entity.setUrlTypeID(cursor.getLong(offset + 2));
        entity.setUrlLocation(cursor.getString(offset + 3));
        entity.setImgFnameID(cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(UrlImgFileTable entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(UrlImgFileTable entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getImgFnameTableDao().getAllColumns());
            builder.append(" FROM URL_IMG_FILE_TABLE T");
            builder.append(" LEFT JOIN IMG_FNAME_TABLE T0 ON T.'IMG_FNAME_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected UrlImgFileTable loadCurrentDeep(Cursor cursor, boolean lock) {
        UrlImgFileTable entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        ImgFnameTable imgFnameTable = loadCurrentOther(daoSession.getImgFnameTableDao(), cursor, offset);
         if(imgFnameTable != null) {
            entity.setImgFnameTable(imgFnameTable);
        }

        return entity;    
    }

    public UrlImgFileTable loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<UrlImgFileTable> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<UrlImgFileTable> list = new ArrayList<UrlImgFileTable>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<UrlImgFileTable> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<UrlImgFileTable> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
